[workspace]
members = ["css-in-rust", "css-in-rust-macros"]
resolver = "2"

[workspace.dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
sha2 = "0.10"
thiserror = "1.0"
